src/jupyterhub_admin/apps/images/urls.py
from django.urls import path
from . import views

app_name = 'images'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:index>', views.images, name='images'),
    path('new/', views.new_image, name='new'),
    path('api/<str:index>', views.api, name='api')
]

src/jupyterhub_admin/apps/jupyterhub/urls.py
from django.urls import path
from . import views

app_name = 'jupyterhub'
urlpatterns = [
    path('', views.index, name='index'),
    path('users/<str:username>', views.user, name='user'),
    path('users/<str:username>/server', views.server, name='server'),
    path('users/<str:username>/view_server', views.view_server, name='view_server')
]

src/jupyterhub_admin/apps/logdata/urls.py
from django.urls import path
from . import views

app_name="logdata"
urlpatterns = [
    path('', views.index, name='index'),
]

src/jupyterhub_admin/apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

src/jupyterhub_admin/apps/mounts/urls.py
from django.urls import path
from . import views

app_name = 'mounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:index>', views.mounts, name='mounts'),
    path('new/', views.new_mount, name='new'),
    path('api/<str:index>', views.api, name='api')
]

src/jupyterhub_admin/urls.py
from django.contrib import admin
from django.urls import include, path
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jhub/', include('jupyterhub_admin.apps.jupyterhub.urls')),
    path('images/', include('jupyterhub_admin.apps.images.urls')),
    path('mounts/', include('jupyterhub_admin.apps.mounts.urls')),
    path('logdata/', include('jupyterhub_admin.apps.logdata.urls')),
    path('auth/', include('jupyterhub_admin.apps.tapisauth.urls')),
    path('', include('jupyterhub_admin.apps.main.urls'))
]

src/jupyterhub_admin/apps/main/views.py
from django.http import HttpResponse
from django.template import loader
from django.conf import settings
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    template = loader.get_template("main/index.html")
    context = {
        'name': f"{settings.TENANT}.{settings.INSTANCE}",
        'server': settings.JUPYTERHUB_SERVER
    }
    return HttpResponse(template.render(context, request))

src/jupyterhub_admin/apps/main/templates/main/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Workbench {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="">
  <link rel="stylesheet" href="">
{% endblock %}
{% block content %}
<h2>JupyterHub Admin Portal</h2>
<p>
  Welcome to the JupyterHub Admin portal.
  <ul>
    <li>
      The tenant instance is <b>{{ name }}</b>
    </li>
    <li>
      You can sign in to the hub at <a href="{{ server }}">{{ server }}</a>
    </li>
  </ul>
</p>
<h3>Hub Configuration</h3>
<ul>
  <li><a href="{% url 'mounts:index' %}">Hub Volume Mounts</a></li>
  <li><a href="{% url 'images:index' %}">Hub Images</a></li>
  <li><a href="{% url 'logdata:index' %}">Hub Usage Data</a></li>
  <li><a href="{% url 'jupyterhub:index' %}">Hub Admin</a></li>
</ul>
{% endblock %}
{% block scripts %}
{% endblock %}