src/jupyterhub_admin/apps/jupyterhub/urls.py
from django.urls import path
from . import views

app_name = 'jupyterhub'
urlpatterns = [
    path('', views.index, name='index'),
    path('users/<str:username>', views.user, name='user'),
    path('users/<str:username>/server', views.server, name='server'),
    path('users/<str:username>/view_server', views.view_server, name='view_server')
]

src/jupyterhub_admin/apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

src/jupyterhub_admin/urls.py
from django.contrib import admin
from django.urls import include, path
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jhub/', include('jupyterhub_admin.apps.jupyterhub.urls')),
    path('images/', include('jupyterhub_admin.apps.images.urls')),
    path('mounts/', include('jupyterhub_admin.apps.mounts.urls')),
    path('logdata/', include('jupyterhub_admin.apps.logdata.urls')),
    path('auth/', include('jupyterhub_admin.apps.tapisauth.urls')),
    path('', include('jupyterhub_admin.apps.main.urls'))
]

src/jupyterhub_admin/apps/jupyterhub/views.py
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.urls import reverse
from jupyterhub_admin.jhub_api import (
    get_users,
    get_user,
    stop_server,
    parse_user,
    has_server,
    start_server,
    get_user_token,
    stop_specified_server
)
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.shortcuts import redirect
import dateutil.parser
import logging


logger = logging.getLogger(__name__)


def format_user(user):
    timeformat = '%Y-%m-%d %H:%M'
    if user['server'] is not None:
        user['server']['started'] = dateutil.parser.isoparse(user['server']['started']).strftime(timeformat)
        user['server']['last_activity'] = dateutil.parser.isoparse(user['server']['last_activity']).strftime(timeformat)
    return user


def apply_sorting(users, sorting=None):
    users = sorted(users, key=lambda user: user['name'])
    if sorting:
        active_users = [ user for user in users if user['server'] ]
        inactive_users = [ user for user in users if not user['server'] ]
        if sorting == 'started':
            active_users = sorted(
                active_users,
                key=lambda user: dateutil.parser.isoparse(user['server']['started']),
                reverse=True
            )
        elif sorting == 'last_activity':
            active_users = sorted(
                active_users,
                key=lambda user: dateutil.parser.isoparse(user['server']['last_activity']),
                reverse=True
            )
        users = active_users + inactive_users
    return users


@login_required
def index(request):
    template = loader.get_template("jupyterhub/index.html")
    sorting = request.GET.get('sorting', None)
    context = {
        'error': False,
        'sorting': sorting,
        'users': []
    }
    try:
        users = [ parse_user(user) for user in get_users() ]
        users = apply_sorting(users, sorting)
        context['users'] = [ format_user(user) for user in users ]
    except Exception as e:
        context['error'] = True
        logger.exception(e)
    return HttpResponse(template.render(context, request))


@login_required
def user(request, username):
    template = loader.get_template("jupyterhub/user.html")
    context = {
        'error': False,
        'message': f'JupyterHub User {username}',
        'servers': [],
        'username': username
    }
    try:
        context['user'] = format_user(parse_user(get_user(username)))
        context['serverNameApi'] = reverse('jupyterhub:stop_server')
        logger.debug(context['user'])
        if len(context['user']['servers']) > 1:
            servers = context['user']['servers']
            servers.pop('')
            for server in servers:
                context['servers'].append(server)
    except Exception as e:
        context['error'] = True
        context['message'] = f'Unable to retrieve JupyterHub user information for {username}'
        logger.exception(e)
    return HttpResponse(template.render(context, request))


@login_required
def server(request, username):
    if request.method == 'DELETE':
        try:
            logger.info(f"Stop server requested for {username}")
            result = stop_server(username)
            if not (result.status_code >= 200 and result.status_code < 300):
                logger.info(result)
                raise Exception(result.text)
            logger.info(f"Stop server successful for {username}")
            return HttpResponse("OK")
        except Exception as e:
            logger.error(f"Stop server failed for {username}")
            logger.exception(e)
            return HttpResponse(status=500)
    elif request.method == 'POST':
        try:
            logger.info(f"Start server requested for {username}")
            result = start_server(username)
            if not (result.status_code >= 200 and result.status_code < 300):
                logger.info(result)
                raise Exception(result.text)
            logger.info(f"Start server successful for {username}")
            return HttpResponse("OK")
        except Exception as e:
            logger.error(f"Start server failed for {username}")
            logger.exception(e)
            return HttpResponse(status=500)

@login_required
def view_server(request, username):
    try:
        response = get_user_token(username)
        token = response['token']
        return redirect(f"{settings.JUPYTERHUB_SERVER}/user/{username}/?token={token}")
    except Exception as e:
        return HttpResponse(status=500)

@login_required
def stop_server(request, username, server):
    stop_specified_server(username, server)
    url = reverse('jupyterhub:user', args=[username])
    return JsonResponse({ 'url': url })

src/jupyterhub_admin/apps/jupyterhub/templates/jupyterhub/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Workbench {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="">
  <link rel="stylesheet" href="">
{% endblock %}
{% block content %}
  <h3>
    JupyterHub Servers
  </h3>
  <p>
    This is a list of users on the JupyterHub. If they currently have a running server,
    you can view it and shut it down. Otherwise, the user is listed as <i>inactive</i>.
  </p>
  {% if error == True %}
    <h4>
      Error retrieving JupyterHub servers
    </h4>
  {% else %}
    <table border=1 class="table">
      <thead>
        <tr>
          <th>
            Username
            {% ifequal sorting None %}
              &#9660;
            {% else %}
              <a href="{% url 'jupyterhub:index' %}">&#9660;</a>
            {% endifequal %}
          </th>
          <th>
            Started
            {% ifequal sorting "started" %}
              &#9660;
            {% else %}
              <a href="{% url 'jupyterhub:index' %}?sorting=started">&#9660;</a>
            {% endifequal %}            
          </th>
          <th>
            Last Activity
            {% ifequal sorting "last_activity" %}
              &#9660;
            {% else %}
              <a href="{% url 'jupyterhub:index' %}?sorting=last_activity">&#9660;</a>
            {% endifequal %}
          </th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td><a href="{% url 'jupyterhub:user' username=user.name %}">{{ user.name }}</a></td>
            <td>
              {% if user.server %}
                {{ user.server.started }}
              {% else %}
                <i>Inactive</i>
              {% endif %}
            </td>
            <td>
              {% if user.server %}
                {{ user.server.last_activity }}
              {% else %}
                <i>Inactive</i>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}
{% block scripts %}
{% endblock %}

src/jupyterhub_admin/apps/jupyterhub/templates/jupyterhub/server_name.html
<div class="modal" role="dialog" id="serverNameModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">User Server</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="username" id="username" value=""/>
        <div class="form-server">
          <label>Please enter a name for the server to delete</label>
          <input
            id="serverName"
            class="form-control"
            type="text"
          />
        </div>
      </div>
      <div class="modal-footer">
        <div id="stopServerError">
          Error trying to stop server
        </div>
        <button type="button" class="btn btn-primary" id="confirmServerName" disabled=true>Enter</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
<script>
  function stopSuccess(data, textStatus, jqXHR) {
    window.location.assign(data.url);
  }

  function stopFailure(jqXHR, textStatus, errorThrown) {
    // Upon failing to save or delete an item, show the error
    $("#stopServerError").show();
  }

  function stopServerApi() {
    $.ajax(
      "{{ serverNameApi  }}",
      {
        method: "DELETE",
        headers: {'X-CSRFToken': '{{ csrf_token }}', 'Content-Type':'application/json'},
        data: JSON.stringify({
          'server': $("#serverName"),
          'username': $("#username")
        }),
        success: stopSuccess,
        error: stopFailure
      }
    )
  }

  $(document).ready(function() {
    username = $(this).data('username');
    $('#username').val(username);
  });
</script>

src/jupyterhub_admin/apps/jupyterhub/templates/jupyterhub/user.html
{% extends "base.html" %}
{% load static %}
{% block title %} Workbench {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="">
  <link rel="stylesheet" href="">
{% endblock %}
{% block content %}
  <h3>
    {{ message }}
  </h3>
  {% if error == True %}
    <div class="alert alert-primary" role="alert">
      {{ message }} 
    </div>
  {% else %}
    {% if user.server %}
      <dl>
        <dt>Started</dt>
        <dd>{{ user.server.started }}</dd>
        <dt>Last Activity</dt>
        <dd>{{ user.server.last_activity }}</dd>
      </dl>
      <a href="{% url 'jupyterhub:view_server' username=user.name %}"
        target="_blank" 
        class="btn btn-secondary active" role="button" aria-pressed="true">
        View User Server 
      </a>
      <button class="btn btn-danger" id="stopServerButton">Stop Server</button>
      {% if servers %}
        <button 
          type="submit" 
          class="btn btn-danger" 
          id="stopSpecServerButton" 
          data-toggle="modal" 
          data-target="#serverNameModal"
          username="{{ username }}"
        >
          Stop Specific Server
        </button>
        <br><br><br>
        <dl>
          <dt>Additional Servers</dt>
          {% for server in servers %}
          <dd>{{ server }}</dd>
          {% endfor %}
        </dl>
      {% endif %}
    {% else %}
      <div>
        <i>This user is currently inactive, and does not have a running server.</i>
      </div>      
      <!-- 
        <button class="btn btn-primary" id="startServerButton">Start Server</button>
      -->
    {% endif %}
    <div class="spinner-border" role="status" id="serverSpinner">
      <span class="sr-only">Loading...</span>
    </div>
    <div id="serverError">
      Error while performing operation on user's server
    </div>
  {% endif %}
{% endblock %}
{% block scripts %}
<script>
  function serverSuccess(data, textStatus, jqXHR) {
    console.log("stop server success", textStatus);
    setTimeout(() => window.location.reload(), 2000);
  }
  function serverError(jqXHR, textStatus, errorThrown) {
    console.log("stop server error", errorThrown);
    $("#serverError").show();
  }
  $(document).ajaxSend(function() {
    $("#serverSpinner").show();
    $("#serverError").hide();
    $("#stopServerButton").prop("disabled", true);
    $("#startServerButton").prop("disabled", true);
  });
  $(document).ajaxStop(function() {
    $("#serverSpinner").hide();
    $("#stopServerButton").prop("disabled", false);
    $("#startServerButton").prop("disabled", false);
  })
  $(document).ready(function() {
    $("#serverSpinner").hide();
    $("#serverError").hide();
    $("#stopServerButton").click(function() {
      $.ajax(
        "{% url 'jupyterhub:server' username=user.name %}",
        {
          method: 'DELETE',
          headers: {'X-CSRFToken': '{{ csrf_token }}'},
          success: serverSuccess,
          error: serverError
        }
      )
    });
    $("#startServerButton").click(function() {
      $.ajax(
        "{% url 'jupyterhub:server' username=user.name %}",
        {
          method: 'POST',
          headers: {'X-CSRFToken': '{{ csrf_token }}'},
            success: serverSuccess,
            error: serverError 
        }
      )
    });
  });
</script>
{% include "jupyterhub/server_name.html" %}
{% endblock %}